### ISSUE TITLE
We have noticed that your account is currently using One Call API quite intensively and exceed the account limit of 1000 calls per day.

### ISSUE THREAD

**Issue by nicocoetzee** [viktak/ha-cc-openweathermap_all#11]
Hello - 

How do I limit the number of API calls? I use OW on my Lovelace dashboard and don't need to use 1,000 calls per day.

Thank you in advance,
n.

**Comment by dgriswo** [comment]
I received the same message from OpenWeatherAPI.  I am not sure if the following error in my logs is the reason for the multiple API calls or if it is a result of the API Key being blocked.

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 487, in async_update_ha_state
    await self.async_device_update()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 691, in async_device_update
    raise exc
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/openweathermap_all/sensor.py", line 184, in update
    self._state = float(owmData["onecall"]["current"]["uvi"])
KeyError: 'current'



Host Operating System | Home Assistant OS 7.4
-- | --
Update Channel | stable
Supervisor Version | supervisor-2022.01.1
Docker Version | 20.10.9

**Comment by nicocoetzee** [comment]
Currently, the integration is not working at all. When does it reset? It's strange as I have never received this error/message before and I've been using it for months.

**Comment by viktak** [comment]
It is the same

**Comment by viktak** [comment]
I have also been using it for as long as it exists and I just received the first warning. Maybe there was a grace period, or they simply hasn't enforced it at all.

**Comment by viktak** [comment]
Please see issue #10 

Please direct further comments there as this is a duplicate.
