### ISSUE TITLE
How to show forccast?

### ISSUE THREAD

**Issue by therealhalifax** [viktak/ha-cc-openweathermap_all#2]
Thanks a lot for that great feature :-) I just see that openweather also offers forcast, but how to show it in Lovelace Mini Graph Card? Any hints?

**Comment by viktak** [comment]
The OpenWeather weather integration is best used with a weather forecast Lovelace UI element as described here: https://www.home-assistant.io/lovelace/weather-forecast/

You can also use a Mini Graph card, but then you have to create a card (or any other UI element) for each forecast item.

**Comment by therealhalifax** [comment]
@viktak thanks for your Feedback. But if I add your Integration accourding your description of the Integration, only Sensors are added, no weather forecast.

**Comment by viktak** [comment]
Yes, I know, this is how I designed it. If you want forecast, you should use the [OpenWeatherMap](https://www.home-assistant.io/integrations/openweathermap/) integration instead, which also provides you with a `Weather` device.
