### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by glendower** [viktak/ha-cc-openweathermap_all#4]
I am probably doing something stupid as I am new to Homeassistant.

I have installed your integration and entered my location and API into configuration.yaml.

But nothing has changed, I can not see any new sensors.

I have the other openweather integration which gives the weather working perfectly

**Comment by glendower** [comment]
OK, it's working now. 
I originally entered my location with 1 decimal place for longitude and latitude. 
This morning I updated that to the full 8 decimal places and everything sprang into life.

Thank you for a great integration

**Comment by viktak** [comment]
Glad it worked out! :)
