### ISSUE TITLE
Index-Sensors

### ISSUE THREAD

**Issue by riwich** [viktak/ha-cc-openweathermap_all#7]
Super useful integration, thanks for that! Is there somewhere (haven't found it yet...) minimum and maximum values plus a rating for the two index sensors "_sensor.owm_pollution_overall_air_quality_" and "_sensor.owm_ultraviolet_index_" ?

Thanks and best regards,
Thomas

**Comment by viktak** [comment]
What do you maximum value? The maximum of last hour? Last day? Last.... ? I think, adding these to this component would slow it down a quite a bit.
What you can do instead, is use a [mini graph card](https://github.com/kalkih/mini-graph-card) to display historical data, which shows max and min values. At least, that's how I do it :). (See the screenshot on the [front page](https://github.com/viktak/ha-cc-openweathermap_all#sample-screenshot-of-sensors-using-mini-graph-card) of this component.

**Comment by riwich** [comment]
Hello viktak, thank you for your response! 
I thought there should be some kind of rating, a scale for the index. Like for example here: [https://aqicn.org/scale/](https://aqicn.org/scale/)
Only to judge which values mean "good", "medium", "poor", etc.
Unfortunately, OpenWeatherMap seems to use a different scale than "AQI".
Anyway, thanks for sharing your work and I will now also use "mini graph card"!

Thomas
