### ISSUE TITLE
slightly different data 

### ISSUE THREAD

**Issue by sdzyubans** [viktak/ha-cc-openweathermap_all#8]
Hi, 

I have found this openweather project on github developed by you, and I am looking for a similar software, so was wondering if you could help me or I could hire you for it - you can share it on github after as well.

basically I have a list of API request strings ( about a 1000 - currently in excel- but format doesnt matter ) for openweather one call and pollution forecast for different geographic coordinates. What i would like to get is a soft which would pull say 20 or 40 of those (chosen by me each time) simultaneously and I would see forecast data plus pollution forecast data hourly for each coordinates for the next 5 hours. It would save me a bunch of time compared to copy and paste API requests into browser one by one. 

Do you think its relatively easy to do?

thank you in advance, 
604-4408007
Serge

**Comment by viktak** [comment]
I'm not sure if this HA component gained anything from this update, so I think a separate component would be more suitable for your request. As such, have you tried using the underlying python module I also wrote: [owm2json](https://github.com/viktak/owm2json) (also on [PyPi](https://pypi.org/project/owm2json)).

You can also simply create a script that takes its input from your database/excel/etc and calls the OWM API directly. I can also write this for you, if you like. If you want to go this way, please contact me directly.

**Comment by sdzyubans** [comment]
Hey my friend, how do I contact you directly and also how much would it
cost to me?

**Comment by viktak** [comment]
I'm sure there is a direct message facility here (although I admit, I haven't found it yet :) )

Also, you can find my contact details on my blog: [https://diy.viktak.com](https://diy.viktak.com)

**Comment by viktak** [comment]
Since I haven't heard from you for a while, I'm assuming you found another solution.
